#!/bin/zsh

alias grob="gfo && groh"
alias cap="cd /mnt/c/Android_Project"
alias wh="whence"
alias ufl="cd /mnt/c/useful"
alias srczsh="source ~/.zshrc"
alias gla="git pull --all"
alias cls="clear"
alias pir="pip install -r requirements.txt "

alias gstb="git stash branch"
alias gc1="git checkout @{-1}"
alias gc2="git checkout @{-2}"
alias gaan="gaa && gcan!"
alias gaanf="gaan && gpf"
alias gaam="gaa && gcam"
alias nanozsh="nano ~/.zshrc && source ~/.zshrc"
alias gcaf!="gcan! && gpf"
alias gradch="git update-index --chmod=+x gradlew"
alias grbi2="git rebase -i HEAD~2"
alias cap="cd /home/madhavth/AndroidProject"
alias capf="cd /home/madhavth/FlutterProject"
alias grld="gcd && gl && gc1 && grbd"
alias grldf="grld && gpf"
alias ggpush='git push -u origin "$(git_current_branch)"'
alias gbc="git branch --show-current"
alias nd="notifyd"
alias gstab="gsta && gstb"

function gcap() {
    msg="$@"
    git commit -a -m "$@" && ggpush
}
